# ~/.config/sesh/sessions/dev-session.yaml
# Sessão de desenvolvimento web full-stack.
name: dev-session
root: ~/workspace/projects/fullstack/my-web-app
windows:
  - name: editor
    layout: main-vertical
    panes:
      - nvim .
  - name: services
    layout: tiled
    panes:
      - npm run dev --prefix ./backend # Inicia o backend
      - npm run dev --prefix ./frontend # Inicia o frontend
  - name: tools
    panes:
      - lazygit