# ╔══════════════════════════════════════════════════════════════════════════╗
# ║              KORA LAZYGIT NEURAL INTERFACE CONFIGURATION               ║
# ║                  ~/.config/lazygit/config.yml                          ║
# ╚══════════════════════════════════════════════════════════════════════════╝

# ████████████████████████████████████████████████████████████████████████████
# █  NEURAL INTERFACE AESTHETICS                                           █
# ████████████████████████████████████████████████████████████████████████████

gui:
  # KORA Neural Color Scheme
  theme:
    lightTheme: false
    activeBorderColor:
      - "#7C3AED"
      - bold
    inactiveBorderColor:
      - "#1A1F29"
    optionsTextColor:
      - "#22D3EE"
    selectedLineBgColor:
      - "#1A1F29"
    selectedRangeBgColor:
      - "#7C3AED"
    cherryPickedCommitBgColor:
      - "#22D3EE"
    cherryPickedCommitFgColor:
      - "#0A0E27"
    unstagedChangesColor:
      - "#F59E0B"
    defaultFgColor:
      - "#CDD6F4"
    searchingActiveBorderColor:
      - "#10B981"

  # Enhanced UI Configuration
  scrollHeight: 2
  scrollPastBottom: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: true
  mainPanelSplitMode: 'flexible'
  enlargedSideViewLocation: 'left'
  language: 'en'
  timeFormat: '02 Jan 06 15:04 MST'
  shortTimeFormat: '15:04'
  
  # KORA Dragon Symbols
  nerdFontsVersion: "3"
  showIcons: true
  showRandomTip: true
  showBranchCommitHash: true
  showFileTree: true
  showListFooter: true
  showCommandLog: true
  commandLogSize: 8
  splitDiff: 'auto'

  # Mouse support for modern terminals
  mouseEvents: true

# ████████████████████████████████████████████████████████████████████████████
# █  GIT WORKFLOW OPTIMIZATION                                              █
# ████████████████████████████████████████████████████████████████████████████

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: false
    
  commit:
    signOff: false
    verbose: default
    
  merging:
    manualCommit: false
    args: ''
    
  log:
    order: 'topo-order'
    showGraph: 'when-maximised'
    showWholeGraph: false
    
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  fetchAll: true
  branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --'
  allBranchesLogCmd: 'git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium'
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: true
  diffContextSize: 3

# ████████████████████████████████████████████████████████████████████████████
# █  ADVANCED KEYBINDING CONFIGURATION                                     █
# ████████████████████████████████████████████████████████████████████████████

keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<c-c>'
    return: '<esc>'
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'
    prevItem: '<up>'
    nextItem: '<down>'
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevPage: ','
    nextPage: '.'
    scrollLeft: 'H'
    scrollRight: 'L'
    gotoTop: '<'
    gotoBottom: '>'
    prevBlock: '<left>'
    nextBlock: '<right>'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    nextMatch: 'n'
    prevMatch: 'N'
    startSearch: '/'
    optionMenu: '<disabled>'
    optionMenu-alt1: '?'
    select: '<space>'
    goInto: '<enter>'
    confirm: '<enter>'
    confirmAlt1: 'y'
    remove: 'd'
    new: 'n'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: '<pgup>'
    scrollDownMain: '<pgdown>'
    scrollUpMain-alt1: 'K'
    scrollDownMain-alt1: 'J'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-d>'
    executeCustomCommand: ':'
    createRebaseOptionsMenu: 'm'
    pushFiles: 'P'
    pullFiles: 'p'
    refresh: 'R'
    createPatchOptionsMenu: '<c-p>'
    nextTab: ']'
    prevTab: '['
    nextScreenMode: '+'
    prevScreenMode: '_'
    undo: 'z'
    redo: '<c-z>'
    filteringMenu: '<c-s>'
    diffingMenu: 'W'
    diffingMenu-alt: '<c-e>'
    copyToClipboard: '<c-o>'
    openRecentRepos: '<c-r>'
    submitEditorText: '<enter>'
    extrasMenu: '@'
    toggleWhitespaceInDiffView: '<c-w>'
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'

  status:
    checkForUpdate: 'u'
    recentRepos: '<enter>'
    allBranchesLogGraph: 'a'

  files:
    commitChanges: 'c'
    commitChangesWithoutHook: 'w'
    amendLastCommit: 'A'
    commitChangesWithEditor: 'C'
    findBaseCommitForFixup: '<c-f>'
    confirmDiscard: 'x'
    ignoreFile: 'i'
    refreshFiles: 'r'
    stashAllChanges: 's'
    viewStashOptions: 'S'
    toggleStagedAll: 'a'
    viewResetOptions: 'D'
    fetch: 'f'
    toggleTreeView: '`'
    openMergeTool: 'M'
    openStatusFilter: '<c-b>'

  branches:
    createPullRequest: 'o'
    viewPullRequestOptions: 'O'
    copyPullRequestURL: '<c-y>'
    checkoutBranchByName: 'c'
    forceCheckoutBranch: 'F'
    rebaseBranch: 'r'
    renameBranch: 'R'
    mergeIntoCurrentBranch: 'M'
    viewGitFlowOptions: 'i'
    fastForward: 'f'
    createTag: 'T'
    pushTag: 'P'
    setUpstream: 'u'
    fetchRemote: 'f'

  worktrees:
    viewWorktreeOptions: 'w'

  commits:
    squashDown: 's'
    renameCommit: 'r'
    renameCommitWithEditor: 'R'
    viewResetOptions: 'g'
    markCommitAsFixup: 'f'
    createFixupCommit: 'F'
    squashAboveCommits: 'S'
    moveDownCommit: '<c-j>'
    moveUpCommit: '<c-k>'
    amendToCommit: 'A'
    pickCommit: 'p'
    revertCommit: 't'
    cherryPickCopy: 'C'
    pasteCommits: 'V'
    markCommitAsBaseForRebase: 'B'
    tagCommit: 'T'
    checkoutCommit: '<space>'
    resetCherryPick: '<c-R>'
    copyCommitAttributeToClipboard: 'y'
    openLogMenu: '<c-l>'
    openInBrowser: 'o'
    viewBisectOptions: 'b'
    startInteractiveRebase: 'i'

  amendAttribute:
    resetAuthor: 'a'
    setAuthor: 'A'
    addCoAuthor: 'c'

  stash:
    popStash: 'g'
    renameStash: 'r'

  commitFiles:
    checkoutCommitFile: 'c'

  main:
    toggleSelectHunk: 'a'
    pickBothHunks: 'b'
    editSelectHunk: 'E'

  submodules:
    init: 'i'
    update: 'u'
    bulkMenu: 'b'

  commitMessage:
    switchToEditor: '<c-o>'

# ████████████████████████████████████████████████████████████████████████████
# █  NEURAL WORKFLOW CUSTOMIZATION                                         █
# ████████████████████████████████████████████████████████████████████████████

os:
  editPreset: 'nvim'
  edit: '{{editor}} {{filename}}'
  editAtLine: '{{editor}} +{{line}} {{filename}}'
  editAtLineAndWait: '{{editor}} +{{line}} {{filename}}'
  open: 'xdg-open {{filename}}'
  openLink: 'xdg-open {{link}}'

refresher:
  refreshInterval: 10
  fetchInterval: 60

update:
  method: prompt
  days: 14

reporting: 'undetermined'

confirmOnQuit: false

quitOnTopLevelReturn: false

disableStartupPopups: false

notARepository: 'prompt'

promptToReturnFromSubprocess: true

# ████████████████████████████████████████████████████████████████████████████
# █  CUSTOM COMMANDS FOR KORA WORKFLOW                                     █
# ████████████████████████████████████████████████████████████████████████████

customCommands:
  - key: 'C'
    command: 'git cz'
    description: 'Commit with Commitizen'
    context: 'files'
    loadingText: 'Creating conventional commit...'
  
  - key: '<c-g>'
    command: 'git log --graph --oneline --all'
    description: 'Graph view of all branches'
    context: 'global'
    subprocess: true
  
  - key: '<c-t>'
    command: 'tig'
    description: 'Open Tig text interface'
    context: 'global'
    subprocess: true
  
  - key: '<c-d>'
    command: 'git diff --name-only --cached | xargs code'
    description: 'Open staged files in VS Code'
    context: 'files'
  
  - key: 'E'
    command: 'nvim {{.SelectedFile.Name}}'
    description: 'Edit file in Neovim'
    context: 'files'
    subprocess: true

# ████████████████████████████████████████████████████████████████████████████
# █  SERVICES AND INTEGRATIONS                                             █
# ████████████████████████████████████████████████████████████████████████████

services:
  'github.com': 'github'
  'gitlab.com': 'gitlab'
  'bitbucket.org': 'bitbucket'
  'gitea.com': 'gitea'
