emulate -L zsh
alias l='eza -lh --icons=auto'
alias ls='eza -1  --icons=auto'
alias ll='eza -lha --icons=auto --sort=name --group-directories-first'
alias ld='eza -lhD --icons=auto'
alias lt='eza --tree --icons=auto'
alias ..='cd ..'; alias ...='cd ../..'
alias .3='cd ../../..'; alias .4='cd ../../../..'; alias .5='cd ../../../../..'
alias gs='git status -sb'
alias ga='git add -A'
alias gc='git commit -m'
alias gp='git push'
alias gl='git log --oneline --graph --decorate -20'
alias d='docker'; alias dc='docker compose'
alias k='kubectl'; alias kg='kubectl get'; alias kd='kubectl describe'; alias kl='kubectl logs'