# ═══════════════════════════════════════════════════════════════════════════════════════════════
# TMUX NEURAL INTERFACE ICONS - GRIMÓRIO NEO-NOIR [REDUZIDO]
# ═══════════════════════════════════════════════════════════════════════════════════════════════
# Uma seleção minimalista e otimizada de ícones Nerd Font para TMUX
# Prioriza as ferramentas mais essenciais para agilidade e clareza
# ═══════════════════════════════════════════════════════════════════════════════════════════════

config:
  fallback-icon: "󰌒"  # Icone padrão para apps desconhecidos
  multi-pane-icon: "󰅙"  # Indicador de múltiplas janelas (panes)
  show-name: false

icons:
  # EDITORES & AMBIENTES DE DESENVOLVIMENTO
  nvim: "󰇸"      # Neovim
  vim: ""        # Vim
  nano: "󰄟"       # Nano
  code: "󰨞"       # VS Code
  vscode: "󰨞"     # VS Code (alt)
  emacs: "󰹑"      # Emacs
  helix: "󰙉"      # Helix

  # SHELLS & TERMINAIS
  fish: "󰈺"       # Fish shell
  zsh: "󰯏"        # Zsh
  bash: "󰌒"       # Bash
  tmux: "󰠘"       # Tmux
  kitty: "󰄛"      # Kitty terminal
  alacritty: "󰒺"   # Alacritty

  # LINGUAGENS & RUNTIMES
  node: "󰎙"       # Node.js
  python: "󰌠"     # Python
  go: "󰟓"         # Go
  rust: "󱥣"       # Rust
  java: "󰈆"       # Java
  php: "󰎜"        # PHP
  typescript: "󰛦" # TypeScript
  javascript: "󰌞" # JavaScript

  # DEVOPS, INFRA & GIT
  docker: "󰡨"       # Docker
  kubernetes: "󱃾"  # Kubernetes
  k8s: "󱃾"        # K8s (alt)
  helm: "󰠳"        # Helm
  terraform: "a"   # Terraform
  git: "󰊢"         # Git
  github: "󰊤"      # GitHub
  gitlab: "󰊧"      # GitLab

  # FERRAMENTAS & UTILITIES
  btop: "󰛚"        # Btop
  htop: "󰛚"        # Htop
  lazygit: "󰊢"     # LazyGit
  npm: "󰆧"         # NPM
  yarn: "󰆞"        # Yarn
  pip: "󰐛"         # Pip
  cargo: "󱨓"       # Cargo
  make: "󰙉"        # Make
  wget: "󰆕"        # Wget
  curl: "󰛶"        # Curl
  ssh: "󰒓"         # SSH
  ls: "󰈙"          # ls
  exa: "󰈙"         # exa
  grep: "󰚃"        # Grep
  find: "󰚃"        # Find
  fzf: "󰈕"         # Fzf
  jq: "󰈱"          # Jq
  yq: "󰈱"          # Yq
  docker-compose: "󰡨"  # Docker Compose

  # SISTEMA & OUTROS
  systemctl: "󰜭"  # Systemctl
  journalctl: "󰜭" # Journalctl
  ps: "󰍛"         # Process list
  top: "󰍛"        # Top
  ping: "󰖓"       # Ping
  traceroute: "󰖓" # Traceroute
  git-delta: "󰈙"  # Git Delta

  # BANCO DE DADOS
  postgres: "󰟎"    # PostgreSQL
  mysql: "󰓶"      # MySQL
  mongodb: "󰊫"     # MongoDB
  redis: "󰛦"       # Redis
