# Arquivo de configuração global para o mise (~/dotfiles/config/mise/config.toml)

# Ferramentas e suas versões globais
# Defina aqui as versões que você quer usar em qualquer lugar do seu sistema.
[tools]
python = "latest"
node = "lts"
go = "latest"
rust = "stable"
lua = "latest"
java = "temurin-21"
maven = "latest"
gradle = "latest"
pnpm = "latest"
yarn = "latest"
bun = "latest"

# Configurações gerais do mise
[settings]
experimental = true
jobs = 4 # Aumenta a velocidade de instalação
shorthands_file = "~/.config/mise/shorthands.toml"

# Exemplo de como definir variáveis de ambiente globais
# [env]
# NPM_CONFIG_PREFIX = "~/.npm-global"