# Arquivo de configuração global para o mise (~/.config/mise/config.toml)

# Ferramentas e suas versões globais
# Descomente e ajuste as versões que deseja usar globalmente.
# Ex: python = "3.11"
[tools]
# python = "latest"
# node = "lts"
# go = "latest"
# rust = "stable"
# lua = "latest"

# Configurações gerais do mise
[settings]
experimental = true # Habilita recursos experimentais
jobs = 4 # Número de jobs paralelos para instalação
shorthands_file = "~/.config/mise/shorthands.toml"
